// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epirocvvdzxiypdvdlwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwaXJvY3Z2ZHp4aXlwZHZkbHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjI1MzgsImV4cCI6MjA2OTkzODUzOH0.Y0VlkV8XqO55En1zTLZ7iinorMHt72O37oFDbhywdTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});